"""Framework-independent semantic core."""

from ontology_core.agent_contract import (
    AgentContractError,
    AgentContractService,
    AgentContractStatus,
    ContractDocument,
)
from ontology_core.authoring import (
    AuthoringError,
    DeprecationDraft,
    EditableResource,
    IndividualDraft,
    RelationDraft,
    RelationIdentity,
    SearchConfirmation,
    TermDraft,
    TermWriter,
    WriteResult,
)
from ontology_core.competency import (
    CompetencyQuestion,
    CompetencyQuestionError,
    CompetencyQuestionRepository,
    CompetencyQuestionResult,
    CompetencyQuestionService,
)
from ontology_core.context import (
    AgentContextPack,
    AgentContextService,
    ContextBudget,
    ContextBudgetError,
    ContextRequest,
)
from ontology_core.detail import ResourceDetail, ResourceDetailService, ResourceUsage
from ontology_core.diff import (
    ProposalReview,
    ProposalReviewService,
    ResourceChange,
    SemanticDiffReport,
    SemanticDiffService,
    SemanticQuad,
)
from ontology_core.forms import FormField, FormSchema, FormSchemaService
from ontology_core.governance import (
    DeprecatedUsage,
    PullRequestGovernanceReport,
    PullRequestGovernanceService,
)
from ontology_core.history import GitHistoryEntry, GitHistoryService
from ontology_core.impact import ImpactReport, ImpactService
from ontology_core.prefixes import NamespaceConfiguration, PrefixResolver
from ontology_core.query import (
    DatasetStats,
    ModuleDescription,
    ModuleStats,
    Neighborhood,
    NeighborhoodFilter,
    NeighborhoodLimits,
    OntologyQueryService,
    QuadView,
    RdfValue,
    ResourceCategory,
    ResourceCategoryCounts,
    ResourceDescription,
    SearchPage,
    SearchResult,
)
from ontology_core.search_receipts import SEARCH_RECEIPT_PATTERN, SearchReceipt
from ontology_core.sparql import (
    ReadOnlySparqlService,
    SparqlLimits,
    SparqlQueryError,
    SparqlResult,
    validate_read_only_query,
)
from ontology_core.store import (
    FilesystemRdfStore,
    KnowledgeStore,
    LocalShapeCatalog,
    RdfLoadError,
    RdfLoadLimits,
)
from ontology_core.validation import (
    SemanticLinter,
    ValidationContext,
    ValidationIssue,
    ValidationReport,
    ValidationResourceType,
    ValidationService,
    ValidationSeverity,
    ValidationSource,
)
from ontology_core.workspace import (
    GitCommit,
    GitCommitResult,
    GitWorkspaceError,
    GitWorkspaceService,
    GitWorkspaceStatus,
    PullRequestResult,
    content_fingerprint,
)

__all__ = [
    "AgentContractError",
    "AgentContractService",
    "AgentContractStatus",
    "ContractDocument",
    "FilesystemRdfStore",
    "AuthoringError",
    "CompetencyQuestion",
    "CompetencyQuestionError",
    "CompetencyQuestionRepository",
    "CompetencyQuestionResult",
    "CompetencyQuestionService",
    "AgentContextPack",
    "AgentContextService",
    "ContextBudget",
    "ContextBudgetError",
    "ContextRequest",
    "ImpactReport",
    "ImpactService",
    "GitHistoryEntry",
    "GitHistoryService",
    "FormField",
    "FormSchema",
    "FormSchemaService",
    "GitCommit",
    "GitCommitResult",
    "GitWorkspaceError",
    "GitWorkspaceService",
    "GitWorkspaceStatus",
    "content_fingerprint",
    "DeprecationDraft",
    "DeprecatedUsage",
    "EditableResource",
    "IndividualDraft",
    "KnowledgeStore",
    "LocalShapeCatalog",
    "DatasetStats",
    "ModuleDescription",
    "ModuleStats",
    "NamespaceConfiguration",
    "Neighborhood",
    "NeighborhoodFilter",
    "NeighborhoodLimits",
    "OntologyQueryService",
    "PrefixResolver",
    "PullRequestResult",
    "PullRequestGovernanceReport",
    "PullRequestGovernanceService",
    "ProposalReview",
    "ProposalReviewService",
    "QuadView",
    "RdfValue",
    "RdfLoadError",
    "RdfLoadLimits",
    "ReadOnlySparqlService",
    "RelationDraft",
    "RelationIdentity",
    "SearchConfirmation",
    "SemanticLinter",
    "SemanticDiffReport",
    "SemanticDiffService",
    "SemanticQuad",
    "ResourceDescription",
    "ResourceChange",
    "ResourceCategoryCounts",
    "ResourceCategory",
    "ResourceDetail",
    "ResourceDetailService",
    "ResourceUsage",
    "SearchResult",
    "SEARCH_RECEIPT_PATTERN",
    "SearchReceipt",
    "SearchPage",
    "SparqlLimits",
    "SparqlQueryError",
    "SparqlResult",
    "TermDraft",
    "TermWriter",
    "ValidationContext",
    "ValidationIssue",
    "ValidationReport",
    "ValidationResourceType",
    "ValidationService",
    "ValidationSeverity",
    "ValidationSource",
    "WriteResult",
    "validate_read_only_query",
    "__version__",
]

__version__ = "0.1.0"
